const maintenance = [
  {day:'18', month:'AGO', title:'Preventiva · G-04', detail:'Prédio administrativo · Equipe Alfa', type:'preventive', label:'PREVENTIVA'},
  {day:'20', month:'AGO', title:'Corretiva · G-02', detail:'Bloco cirúrgico · Marcos Silva', type:'corrective', label:'CORRETIVA'},
  {day:'26', month:'AGO', title:'Preventiva · G-07', detail:'Casa de máquinas · Equipe Alfa', type:'preventive', label:'PREVENTIVA'},
  {day:'02', month:'SET', title:'Preventiva · G-01', detail:'Prédio principal · A definir', type:'preventive', label:'PREVENTIVA'}
];
const orders = [
  {id:'OS-0024', generator:'G-02 · Bloco cirúrgico', type:'Corretiva', person:'Marcos Silva', due:'20 AGO 2026', status:'open', statusLabel:'Aberta'},
  {id:'OS-0023', generator:'G-04 · Prédio administrativo', type:'Preventiva', person:'Equipe Alfa', due:'18 AGO 2026', status:'progress', statusLabel:'Em andamento'},
  {id:'OS-0022', generator:'G-08 · Almoxarifado', type:'Preventiva', person:'Equipe Alfa', due:'12 AGO 2026', status:'done', statusLabel:'Concluída'}
];
const $ = (selector) => document.querySelector(selector);
function renderMaintenance(){ $('#maintenance-list').innerHTML = maintenance.map(item => `<div class="timeline-row"><div class="timeline-date"><strong>${item.day}</strong>${item.month}</div><div class="timeline-marker"></div><div class="timeline-info"><strong>${item.title}</strong><small>${item.detail}</small></div><span class="tag ${item.type}">${item.label}</span></div>`).join(''); }
function renderOrders(){ $('#orders-table').innerHTML = orders.map(order => `<tr><td>${order.id}</td><td><strong>${order.generator.split(' · ')[0]}</strong><small>${order.generator.split(' · ')[1]}</small></td><td>${order.type}</td><td>${order.person}</td><td>${order.due}</td><td><span class="status ${order.status}">${order.statusLabel}</span></td><td class="row-more">•••</td></tr>`).join(''); }
function openModal(){ $('#modal-backdrop').classList.remove('hidden'); document.body.style.overflow='hidden'; }
function closeModal(){ $('#modal-backdrop').classList.add('hidden'); document.body.style.overflow=''; }
function setView(view){ const labels={geradores:['CADASTRO DE ATIVOS','Geradores','Os 11 ativos do hospital serão cadastrados e acompanhados nesta área.'],ordens:['GESTÃO OPERACIONAL','Ordens de serviço','Abertura, execução e fechamento de cada atendimento.'],agenda:['PLANEJAMENTO','Agenda','Visualize as preventivas e corretivas programadas.'], 'visao-geral':['PAINEL DE OPERAÇÃO','Visão geral','']}; const data=labels[view]||labels['visao-geral']; document.querySelectorAll('.nav-item').forEach(item=>item.classList.toggle('active',item.dataset.view===view)); $('#breadcrumb-title').textContent=data[1]; $('#page-title').innerHTML=view==='visao-geral'?'Bom dia, Marcos<span>.</span>':data[1]; $('#dashboard-view').classList.toggle('hidden',view!=='visao-geral'); $('#secondary-view').classList.toggle('hidden',view==='visao-geral'); $('#secondary-eyebrow').textContent=data[0]; $('#secondary-title').textContent=data[1]; $('#secondary-copy').textContent=data[2]; $('#empty-action').textContent=view==='geradores'?'＋ Cadastrar gerador':'＋ Nova ordem de serviço'; $('#empty-action').onclick=view==='geradores'?()=>alert('Cadastro de gerador será conectado ao banco na próxima etapa.'):openModal; }
document.addEventListener('DOMContentLoaded',()=>{ renderMaintenance(); renderOrders(); $('#new-os-button').onclick=openModal; $('#modal-close').onclick=closeModal; $('#modal-backdrop').addEventListener('click',e=>{if(e.target.id==='modal-backdrop')closeModal()}); document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()}); document.querySelectorAll('[data-view]').forEach(item=>item.addEventListener('click',()=>setView(item.dataset.view))); document.querySelectorAll('[data-view-target]').forEach(item=>item.addEventListener('click',()=>setView(item.dataset.viewTarget))); document.querySelectorAll('.filter').forEach(item=>item.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(button=>button.classList.remove('active'));item.classList.add('active')})); $('#os-form').addEventListener('submit',e=>{e.preventDefault();closeModal();alert('Ordem de serviço criada. O fluxo de persistência será conectado na próxima etapa.');}); });
