'use client';
import { FormEvent, useEffect, useState } from 'react';
import styles from './planning-panel.module.css';
import { atualizarPlanejamento, apagarPlanejamento, criarPlanejamento, listarGeradores, listarPlanejamentos, type Gerador, type Planejamento, type PlanejamentoInput } from '../lib/api';
const hoje = new Date();
function proximaData(mes: number, dia: number) { const ano = hoje.getFullYear(); const data = new Date(ano, mes - 1, dia); return (data < hoje ? new Date(ano + 1, mes - 1, dia) : data).toISOString().slice(0, 10); }
const vazio: PlanejamentoInput = { gerador_id: '', empresa_nome: '', empresa_email: '', mes_execucao: hoje.getMonth() + 1, dia_execucao: 1, troca_oleo_filtros: true, periodicidade_bateria_anos: 2, ultima_bateria: null, proxima_data: proximaData(hoje.getMonth() + 1, 1) };
const meses = ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
export default function PlanningPanel() { const [geradores,setGeradores]=useState<Gerador[]>([]); const [planos,setPlanos]=useState<Planejamento[]>([]); const [form,setForm]=useState(vazio); const [editando,setEditando]=useState<Planejamento|null>(null); const [erro,setErro]=useState(''); const [salvando,setSalvando]=useState(false);
  async function carregar(){const [g,p]=await Promise.all([listarGeradores(),listarPlanejamentos()]);setGeradores(g.geradores);setPlanos(p.planejamentos)} useEffect(()=>{carregar().catch(e=>setErro(e instanceof Error?e.message:'Não foi possível carregar o planejamento'))},[]);
  function alterar(campo:keyof PlanejamentoInput,valor:string|boolean){setForm(a=>({...a,[campo]:valor,...(campo==='mes_execucao'||campo==='dia_execucao'?{proxima_data:proximaData(campo==='mes_execucao'?Number(valor):a.mes_execucao,campo==='dia_execucao'?Number(valor):a.dia_execucao)}:{})}))}
  function editar(p:Planejamento){setEditando(p);setForm({gerador_id:p.gerador_id,empresa_nome:p.empresa_nome,empresa_email:p.empresa_email,mes_execucao:p.mes_execucao,dia_execucao:p.dia_execucao,troca_oleo_filtros:p.troca_oleo_filtros,periodicidade_bateria_anos:p.periodicidade_bateria_anos,ultima_bateria:p.ultima_bateria,proxima_data:p.proxima_data.slice(0,10)})}
  function novo(){setEditando(null);setForm({...vazio,proxima_data:proximaData(vazio.mes_execucao,1)});setErro('')}
  async function salvar(e:FormEvent){e.preventDefault();setSalvando(true);setErro('');try{if(editando)await atualizarPlanejamento(editando.id,form);else await criarPlanejamento(form);await carregar();novo()}catch(e){setErro(e instanceof Error?e.message:'Não foi possível salvar')}finally{setSalvando(false)}}
  async function apagar(p:Planejamento){if(!window.confirm(`Remover o planejamento do ${p.gerador_nome}?`))return;try{await apagarPlanejamento(p.id);await carregar()}catch(e){setErro(e instanceof Error?e.message:'Não foi possível remover')}}
  return <section className={styles.shell} id="planejamento"><div className={styles.heading}><p className="eyebrow">PLANEJAMENTO PREVENTIVO</p><h1>Manutenção anual dos geradores</h1><p>Programe óleo e filtros todos os anos e acompanhe a troca de bateria a cada dois anos.</p></div><form className={styles.form} onSubmit={salvar}><label>Gerador<select required value={form.gerador_id} onChange={e=>alterar('gerador_id',e.target.value)}><option value="">Selecione</option>{geradores.map(g=><option key={g.id} value={g.id}>{g.identificacao}</option>)}</select></label><label>Empresa vencedora do pregão<input required value={form.empresa_nome} onChange={e=>alterar('empresa_nome',e.target.value)}/></label><label>E-mail da empresa<input type="email" required value={form.empresa_email} onChange={e=>alterar('empresa_email',e.target.value)}/></label><label>Mês<select value={form.mes_execucao} onChange={e=>alterar('mes_execucao',e.target.value)}>{meses.map((m,i)=><option key={m} value={i+1}>{m}</option>)}</select></label><label>Dia<select value={form.dia_execucao} onChange={e=>alterar('dia_execucao',e.target.value)}>{Array.from({length:28},(_,i)=><option key={i+1} value={i+1}>{i+1}</option>)}</select></label><label className={styles.check}><input type="checkbox" checked={form.troca_oleo_filtros} onChange={e=>alterar('troca_oleo_filtros',e.target.checked)}/> Trocar óleo e filtros</label><label>Última troca da bateria<input type="date" value={form.ultima_bateria??''} onChange={e=>alterar('ultima_bateria',e.target.value)}/></label><label>Periodicidade da bateria<select value={form.periodicidade_bateria_anos} onChange={e=>alterar('periodicidade_bateria_anos',e.target.value)}><option value="2">A cada 2 anos</option><option value="1">Anualmente</option><option value="3">A cada 3 anos</option></select></label><div className={styles.actions}><button type="button" onClick={novo}>Limpar</button><button className={styles.primary} disabled={salvando}>{salvando?'Salvando...':editando?'Salvar edição':'Adicionar ao planejamento'}</button></div></form>{erro&&<p className={styles.error}>{erro}</p>}<div className={styles.list}>{planos.map(p=><article className={styles.card} key={p.id}><strong>{p.gerador_nome}</strong><span>{meses[p.mes_execucao-1]} de cada ano, dia {p.dia_execucao} · {p.empresa_nome}</span><small>{p.troca_oleo_filtros?'Óleo e filtros anuais':''}{p.ultima_bateria?` · Bateria: ${p.periodicidade_bateria_anos} em ${p.ultima_bateria.slice(0,10)}`:' · Bateria a controlar'}</small><small>Lembrete por e-mail: um mês antes · {p.empresa_email}</small><button onClick={()=>editar(p)}>Editar</button><button onClick={()=>apagar(p)}>Remover</button></article>)}{!planos.length&&<p className={styles.empty}>Nenhum gerador planejado.</p>}</div></section>;
}
