'use client';
import { useState } from 'react';
import styles from './supervisory-panel.module.css';
import { type Gerador } from '../lib/api';

type Props = { geradores: Gerador[]; podeEditar: boolean; novoGerador: () => void };
type Status = 'funcionando' | 'alerta' | 'parado' | 'sem_telemetria';
const labels: Record<Status, string> = { funcionando: 'Funcionando', alerta: 'Alerta', parado: 'Parado', sem_telemetria: 'Sem telemetria' };
const vazio = '\u2014';
const ler = (g: Gerador, ...keys: string[]) => keys.map((key) => g.dados_tecnicos?.[key]).find(Boolean) ?? vazio;
function status(g: Gerador): Status { const value = String(g.dados_tecnicos?.status ?? g.dados_tecnicos?.estado ?? '').toLowerCase(); if (/(funcion|running|operando|partid)/.test(value)) return 'funcionando'; if (/(alert|falha|alarme|warning)/.test(value)) return 'alerta'; if (/(parad|stopped|deslig)/.test(value)) return 'parado'; return 'sem_telemetria'; }
function Gauge({ rpm }: { rpm: string }) { return <div className={styles.gauge} aria-label={'Rotacao do motor: ' + rpm + ' RPM'}><div className={styles.gaugeRing}><span className={styles.gaugeNeedle} /></div><strong>{rpm}</strong><small>RPM</small></div>; }
function Metric({ label, value, unit, accent }: { label: string; value: string; unit: string; accent?: boolean }) { return <article className={styles.metric}><span>{label}</span><strong className={accent ? styles.metricAccent : ''}>{value}<small>{value === vazio ? '' : unit}</small></strong></article>; }
function Details({ initial, back }: { initial: Gerador; back: () => void }) {
  const [gerador, setGerador] = useState(initial); const state = status(gerador);
  const secondary: [string, string, string, boolean?][] = [['Frequencia', ler(gerador, 'frequencia', 'frequencia_hz'), 'Hz'], ['Carga ativa', ler(gerador, 'kw', 'potencia_kw', 'carga_kw'), 'kW'], ['Combustivel', ler(gerador, 'combustivel', 'nivel_combustivel'), '%'], ['Bateria', ler(gerador, 'bateria', 'tensao_bateria'), 'V'], ['Temperatura', ler(gerador, 'temperatura', 'temperatura_motor'), 'C']];
  const voltage = [ler(gerador, 'tensao_l1', 'tensao_fase_l1', 'tensao_f1'), ler(gerador, 'tensao_l2', 'tensao_fase_l2', 'tensao_f2'), ler(gerador, 'tensao_l3', 'tensao_fase_l3', 'tensao_f3')];
  const current = [ler(gerador, 'corrente_l1', 'corrente_fase_l1', 'corrente_f1'), ler(gerador, 'corrente_l2', 'corrente_fase_l2', 'corrente_f2'), ler(gerador, 'corrente_l3', 'corrente_fase_l3', 'corrente_f3')];
  const mains = [ler(gerador, 'rede_tensao_l1', 'tensao_rede_l1', 'mains_tensao_l1'), ler(gerador, 'rede_tensao_l2', 'tensao_rede_l2', 'mains_tensao_l2'), ler(gerador, 'rede_tensao_l3', 'tensao_rede_l3', 'mains_tensao_l3')];
  const phaseNames = ['L1', 'L2', 'L3'];
  return <section className={styles.detailShell}><div className={styles.detailTop}><button className={styles.backButton} onClick={back}>&larr; Frota</button><span className={styles.lastUpdate}>TELEMETRIA OPERACIONAL</span></div><header className={styles.detailHeader}><div><p className={styles.kicker}>SUPERVISORIO / EQUIPAMENTO</p><h1>{gerador.identificacao}</h1><p>{gerador.predio} &middot; {gerador.localizacao}</p></div><span className={styles.statusPill + ' ' + styles[state]}><i />{labels[state]}</span></header><div className={styles.mainGrid}><section className={styles.telemetryCard}><div className={styles.sectionHead}><div><p className={styles.kicker}>MOTOR E GERADOR</p><h2>Leituras agora</h2></div><span className={styles.liveTag}><i /> ao vivo</span></div><div className={styles.telemetryBody}><div className={styles.gaugeWrap}><Gauge rpm={ler(gerador, 'rpm', 'rotacao_rpm', 'velocidade_motor')} /><span className={styles.controller}>Controlador <strong>{ler(gerador, 'controlador', 'usca_modelo')}</strong></span></div><div className={styles.metrics}>{secondary.map(([label, value, unit]) => <Metric key={label} label={label} value={value} unit={unit} />)}</div></div></section><section className={styles.phaseCard}><div className={styles.sectionHead}><div><p className={styles.kicker}>SAIDA DO GERADOR</p><h2>Grandezas por fase</h2></div><span className={styles.readOnly}>3 fases</span></div><div className={styles.phaseColumns}><div><span className={styles.groupLabel}>Tensao</span><div className={styles.phaseGrid}>{voltage.map((value, index) => <Metric key={'v'+index} label={phaseNames[index]} value={value} unit="V" accent />)}</div></div><div><span className={styles.groupLabel}>Corrente</span><div className={styles.phaseGrid}>{current.map((value, index) => <Metric key={'i'+index} label={phaseNames[index]} value={value} unit="A" />)}</div></div></div></section><section className={styles.networkCard}><div className={styles.sectionHead}><div><p className={styles.kicker}>REDE ELETRICA</p><h2>Tensao da rede</h2></div><span className={styles.readOnly}>Entrada</span></div><div className={styles.phaseGrid}>{mains.map((value, index) => <Metric key={'r'+index} label={phaseNames[index]} value={value} unit="V" accent />)}</div></section><section className={styles.alertCard}><div className={styles.sectionHead}><div><p className={styles.kicker}>SEGURANCA</p><h2>Alarmes</h2></div><span className={styles.alertCount}>0 eventos</span></div><div className={styles.noAlarm}><span>OK</span><div><strong>Nenhum alarme recebido</strong><small>Sem eventos disponiveis para este equipamento.</small></div></div></section></div></section>;
}

export default function SupervisoryPanel({ geradores, podeEditar, novoGerador }: Props) { const [selected, setSelected] = useState<Gerador | null>(null); if (selected) return <Details initial={selected} back={() => setSelected(null)} />; const counts = (['funcionando', 'alerta', 'parado'] as Status[]).map((value) => geradores.filter((g) => status(g) === value).length); return <section className={styles.shell}><header className={styles.heading}><div><p className={styles.kicker}>SUPERVISORIO / VISAO RAPIDA</p><h1>Situacao da frota</h1><p>Selecione um gerador para acompanhar o estado e a comunicacao.</p></div><div className={styles.summary}><strong>{geradores.length}</strong><span>equipamentos</span></div></header><div className={styles.statusBar}><span><i className={styles.dotGreen} />{counts[0]} funcionando</span><span><i className={styles.dotAmber} />{counts[1]} em alerta</span><span><i className={styles.dotSlate} />{counts[2]} parados</span></div>{geradores.length === 0 ? <div className={styles.empty}><strong>Nenhum gerador cadastrado</strong><span>Cadastre um equipamento para iniciar o supervisorio.</span>{podeEditar && <button onClick={novoGerador}>+ Cadastrar gerador</button>}</div> : <div className={styles.fleetGrid}>{geradores.map((gerador, index) => { const state = status(gerador); return <button className={styles.fleetCard} key={gerador.id} onClick={() => setSelected(gerador)}><span className={styles.cardIndex}>{String(index + 1).padStart(2, '0')}</span><span className={styles.fleetName}>{gerador.identificacao}</span><span className={styles.cardStatus + ' ' + styles[state]}><i />{labels[state]}</span><span className={styles.fleetLocation}>{gerador.predio} &middot; {gerador.localizacao}</span><span className={styles.openHint}>Abrir <b>&nearr;</b></span></button>; })}</div>}{podeEditar && geradores.length > 0 && <button className={styles.addButton} onClick={novoGerador}>+ Novo gerador</button>}</section>; }
