import { pool } from './db.js';
import { registrarAuditoria } from './auditoria.js';
export type EmpresaInput = { nome: string; cnpj: string; telefone?: string | null; email?: string | null; endereco?: string | null; cidade?: string | null; contato?: string | null };
const texto = (v: unknown) => typeof v === 'string' ? v.trim() : '';
export function validarEmpresa(input: Partial<EmpresaInput>, parcial = false): EmpresaInput | Partial<EmpresaInput> { const r: Partial<EmpresaInput> = {}; for (const campo of ['nome', 'cnpj'] as const) if (!parcial || input[campo] !== undefined) { r[campo] = texto(input[campo]); if (!r[campo]) throw new Error(`${campo} é obrigatório`); } for (const campo of ['telefone', 'email', 'endereco', 'cidade', 'contato'] as const) if (input[campo] !== undefined) r[campo] = texto(input[campo]) || null; if (r.email && !/^\S+@\S+\.\S+$/.test(r.email)) throw new Error('e-mail da empresa inválido'); return r; }
export async function listarEmpresas() { return (await pool.query('select * from empresa where ativo=true order by nome')).rows; }
export async function criarEmpresa(input: EmpresaInput, usuarioId: string) { const client = await pool.connect(); try { await client.query('begin'); const result = await client.query(`insert into empresa (nome,cnpj,telefone,email,endereco,cidade,contato,criado_por,atualizado_por) values ($1,$2,$3,$4,$5,$6,$7,$8,$8) returning *`, [input.nome, input.cnpj, input.telefone ?? null, input.email ?? null, input.endereco ?? null, input.cidade ?? null, input.contato ?? null, usuarioId]); await registrarAuditoria(client, usuarioId, 'empresa', result.rows[0].id, 'criar', null, result.rows[0]); await client.query('commit'); return result.rows[0]; } catch (error) { await client.query('rollback'); throw error; } finally { client.release(); } }
export async function atualizarEmpresa(id: string, input: Partial<EmpresaInput>, usuarioId: string) { const client = await pool.connect(); try { await client.query('begin'); const old = await client.query('select * from empresa where id=$1 and ativo=true for update', [id]); if (!old.rowCount) throw new Error('empresa não encontrada'); const a = { ...old.rows[0], ...input }; const result = await client.query(`update empresa set nome=$1,cnpj=$2,telefone=$3,email=$4,endereco=$5,cidade=$6,contato=$7,atualizado_por=$8,atualizado_em=now() where id=$9 returning *`, [a.nome, a.cnpj, a.telefone ?? null, a.email ?? null, a.endereco ?? null, a.cidade ?? null, a.contato ?? null, usuarioId, id]); await registrarAuditoria(client, usuarioId, 'empresa', id, 'atualizar', old.rows[0], result.rows[0]); await client.query('commit'); return result.rows[0]; } catch (error) { await client.query('rollback'); throw error; } finally { client.release(); } }
export async function apagarEmpresa(id: string, usuarioId: string) { const client = await pool.connect(); try { await client.query('begin'); const old = await client.query('select * from empresa where id=$1 and ativo=true for update', [id]); if (!old.rowCount) throw new Error('empresa não encontrada'); const result = await client.query('update empresa set ativo=false,atualizado_por=$1,atualizado_em=now() where id=$2 returning *', [usuarioId, id]); await registrarAuditoria(client, usuarioId, 'empresa', id, 'desativar', old.rows[0], result.rows[0]); await client.query('commit'); } catch (error) { await client.query('rollback'); throw error; } finally { client.release(); } }
