import { pool } from './db.js';
export type PlanejamentoInput = { gerador_id: string; empresa_id: string; mes_execucao: number; dia_execucao: number; troca_oleo_filtros: boolean; periodicidade_bateria_anos: number; ultima_bateria?: string | null; proxima_data: string };
function texto(v: unknown) { return typeof v === 'string' ? v.trim() : ''; }
function inteiro(v: unknown) { const n=Number(v); return Number.isInteger(n) ? n : 0; }
export function validarPlanejamento(input: Partial<PlanejamentoInput>, parcial=false): PlanejamentoInput|Partial<PlanejamentoInput> { const r:Partial<PlanejamentoInput>={}; for(const c of ['gerador_id','empresa_id','proxima_data'] as const) if(!parcial||input[c]!==undefined){r[c]=texto(input[c]);if(!r[c])throw new Error(`${c} é obrigatório`)} if(!parcial||input.mes_execucao!==undefined)r.mes_execucao=inteiro(input.mes_execucao);if(!parcial||input.dia_execucao!==undefined)r.dia_execucao=inteiro(input.dia_execucao);if(!parcial||input.periodicidade_bateria_anos!==undefined)r.periodicidade_bateria_anos=inteiro(input.periodicidade_bateria_anos);if(r.mes_execucao!==undefined&&(r.mes_execucao<1||r.mes_execucao>12))throw new Error('mês de execução inválido');if(r.dia_execucao!==undefined&&(r.dia_execucao<1||r.dia_execucao>28))throw new Error('dia de execução inválido');if(r.periodicidade_bateria_anos!==undefined&&(r.periodicidade_bateria_anos<1||r.periodicidade_bateria_anos>10))throw new Error('periodicidade da bateria inválida');if(!parcial||input.troca_oleo_filtros!==undefined)r.troca_oleo_filtros=input.troca_oleo_filtros!==false;if(input.ultima_bateria!==undefined)r.ultima_bateria=texto(input.ultima_bateria)||null;return r; }
async function empresa(id:string){const r=await pool.query('select nome,email from empresa where id=$1 and ativo=true',[id]);if(!r.rowCount)throw new Error('empresa não encontrada');return r.rows[0];}
export async function listarPlanejamentos(){const r=await pool.query(`select p.*,g.identificacao as gerador_nome,coalesce(e.nome,p.empresa_nome) as empresa_nome,coalesce(e.email,p.empresa_email) as empresa_email from planejamento_preventivo p join gerador g on g.id=p.gerador_id left join empresa e on e.id=p.empresa_id where p.ativo=true order by p.proxima_data,g.identificacao`);return r.rows;}
export async function criarPlanejamento(input:PlanejamentoInput,usuarioId:string){const e=await empresa(input.empresa_id);const r=await pool.query(`insert into planejamento_preventivo (gerador_id,empresa_id,empresa_nome,empresa_email,mes_execucao,dia_execucao,troca_oleo_filtros,periodicidade_bateria_anos,ultima_bateria,proxima_data,criado_por) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning *`,[input.gerador_id,input.empresa_id,e.nome,e.email,input.mes_execucao,input.dia_execucao,input.troca_oleo_filtros,input.periodicidade_bateria_anos,input.ultima_bateria??null,input.proxima_data,usuarioId]);return r.rows[0];}
export async function atualizarPlanejamento(id:string,input:Partial<PlanejamentoInput>){const old=await pool.query('select * from planejamento_preventivo where id=$1 and ativo=true',[id]);if(!old.rowCount)throw new Error('planejamento não encontrado');const a={...old.rows[0],...input};const e=await empresa(a.empresa_id);const r=await pool.query(`update planejamento_preventivo set gerador_id=$1,empresa_id=$2,empresa_nome=$3,empresa_email=$4,mes_execucao=$5,dia_execucao=$6,troca_oleo_filtros=$7,periodicidade_bateria_anos=$8,ultima_bateria=$9,proxima_data=$10,atualizado_em=now(),lembrete_enviado_em=null where id=$11 returning *`,[a.gerador_id,a.empresa_id,e.nome,e.email,a.mes_execucao,a.dia_execucao,a.troca_oleo_filtros,a.periodicidade_bateria_anos,a.ultima_bateria??null,a.proxima_data,id]);return r.rows[0];}
export async function apagarPlanejamento(id:string){const r=await pool.query('update planejamento_preventivo set ativo=false,atualizado_em=now() where id=$1 and ativo=true returning id',[id]);if(!r.rowCount)throw new Error('planejamento não encontrado');}