import { pool } from './db.js';
import { registrarAuditoria } from './auditoria.js';
export type PlanejamentoInput = { gerador_id: string; empresa_id: string; mes_execucao: number; dia_execucao: number; troca_oleo_filtros: boolean; periodicidade_bateria_anos: number; ultima_bateria?: string | null; proxima_data: string };
function texto(v: unknown) { return typeof v === 'string' ? v.trim() : ''; }
function inteiro(v: unknown) { const n = Number(v); return Number.isInteger(n) ? n : 0; }
export function validarPlanejamento(input: Partial<PlanejamentoInput>, parcial = false): PlanejamentoInput | Partial<PlanejamentoInput> { const r: Partial<PlanejamentoInput> = {}; for (const c of ['gerador_id', 'empresa_id', 'proxima_data'] as const) if (!parcial || input[c] !== undefined) { r[c] = texto(input[c]); if (!r[c]) throw new Error(`${c} é obrigatório`); } if (!parcial || input.mes_execucao !== undefined) r.mes_execucao = inteiro(input.mes_execucao); if (!parcial || input.dia_execucao !== undefined) r.dia_execucao = inteiro(input.dia_execucao); if (!parcial || input.periodicidade_bateria_anos !== undefined) r.periodicidade_bateria_anos = inteiro(input.periodicidade_bateria_anos); if (r.mes_execucao !== undefined && (r.mes_execucao < 1 || r.mes_execucao > 12)) throw new Error('mês de execução inválido'); if (r.dia_execucao !== undefined && (r.dia_execucao < 1 || r.dia_execucao > 28)) throw new Error('dia de execução inválido'); if (r.periodicidade_bateria_anos !== undefined && (r.periodicidade_bateria_anos < 1 || r.periodicidade_bateria_anos > 10)) throw new Error('periodicidade da bateria inválida'); if (!parcial || input.troca_oleo_filtros !== undefined) r.troca_oleo_filtros = input.troca_oleo_filtros !== false; if (input.ultima_bateria !== undefined) r.ultima_bateria = texto(input.ultima_bateria) || null; return r; }
export async function listarPlanejamentos() { return (await pool.query(`select p.*, g.identificacao as gerador_nome, e.nome as empresa_nome, e.email as empresa_email from planejamento_preventivo p join gerador g on g.id=p.gerador_id join empresa e on e.id=p.empresa_id where p.ativo=true order by p.proxima_data,g.identificacao`)).rows; }
export async function criarPlanejamento(input: PlanejamentoInput, usuarioId: string) { return (await pool.query(`insert into planejamento_preventivo (gerador_id,empresa_id,mes_execucao,dia_execucao,troca_oleo_filtros,periodicidade_bateria_anos,ultima_bateria,proxima_data,criado_por,atualizado_por) values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$9) returning *`, [input.gerador_id, input.empresa_id, input.mes_execucao, input.dia_execucao, input.troca_oleo_filtros, input.periodicidade_bateria_anos, input.ultima_bateria ?? null, input.proxima_data, usuarioId])).rows[0]; }
export async function atualizarPlanejamento(id: string, input: Partial<PlanejamentoInput>, usuarioId: string) { const client = await pool.connect(); try { await client.query('begin'); const old = await client.query('select * from planejamento_preventivo where id=$1 and ativo=true for update', [id]); if (!old.rowCount) throw new Error('planejamento não encontrado'); const a = { ...old.rows[0], ...input }; const result = await client.query(`update planejamento_preventivo set gerador_id=$1,empresa_id=$2,mes_execucao=$3,dia_execucao=$4,troca_oleo_filtros=$5,periodicidade_bateria_anos=$6,ultima_bateria=$7,proxima_data=$8,atualizado_por=$9,atualizado_em=now(),lembrete_enviado_em=null where id=$10 returning *`, [a.gerador_id, a.empresa_id, a.mes_execucao, a.dia_execucao, a.troca_oleo_filtros, a.periodicidade_bateria_anos, a.ultima_bateria ?? null, a.proxima_data, usuarioId, id]); await registrarAuditoria(client, usuarioId, 'planejamento_preventivo', id, 'atualizar', old.rows[0], result.rows[0]); await client.query('commit'); return result.rows[0]; } catch (error) { await client.query('rollback'); throw error; } finally { client.release(); } }
export async function apagarPlanejamento(id: string, usuarioId: string) { const client = await pool.connect(); try { await client.query('begin'); const old = await client.query('select * from planejamento_preventivo where id=$1 and ativo=true for update', [id]); if (!old.rowCount) throw new Error('planejamento não encontrado'); const result = await client.query('update planejamento_preventivo set ativo=false,atualizado_por=$1,atualizado_em=now() where id=$2 returning *', [usuarioId, id]); await registrarAuditoria(client, usuarioId, 'planejamento_preventivo', id, 'desativar', old.rows[0], result.rows[0]); await client.query('commit'); } catch (error) { await client.query('rollback'); throw error; } finally { client.release(); } }
